name: Deploy Frontend

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for testing
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .

      - name: Run tests in Docker container
        run: docker run -e CI=true cygnetops/react-test npm test
